-- select
select * from reserve;
select * from service;
select * from member;
-- 공지사항
select * from article where board_id=0;
-- 이벤트
select * from article where board_id=1;
select count(*) as listCnt from article where board_id=1;
select @rownum:=@rownum+1 as no, A.* from article A where (@rownum:=0)=0 AND board_id=1 order by A.article_id desc LIMIT 1,10;
select @rownum:=@rownum+1 as no, A.* from article A where (@rownum:=0)=0 AND A.board_id=1 order by no desc;
-- Q&A
select * from article where board_id=2;

select count(*) as listCnt from article where board_id=0;
-- insert
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항1','내용1',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항2','내용2',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항3','내용3',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항4','내용4',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항5','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항6','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항7','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항8','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항9','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항10','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항11','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항12','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항13','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항14','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항15','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항16','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항17','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항18','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항19','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항20','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항21','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항22','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항23','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항24','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항25','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항26','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항27','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항28','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항29','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항30','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항31','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항32','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항33','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항34','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항35','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항36','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항37','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항38','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항39','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항40','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항41','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항42','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항43','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항44','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항45','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항46','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항47','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항48','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항49','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항50','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항51','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항52','내용5',now());
insert into notice (ntc_title,ntc_content,ntc_date) values ('공지사항53','내용5',now());
commit;