-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 17:10:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema companion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema companion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `companion` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `companion` ;

-- -----------------------------------------------------
-- Table `companion`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`member` (
  `mb_id` VARCHAR(20) NOT NULL COMMENT '아이디',
  `mb_pw` VARCHAR(30) NOT NULL COMMENT '비밀번호',
  `mb_name` VARCHAR(10) NOT NULL COMMENT '이름',
  `mb_tel` VARCHAR(13) NULL DEFAULT NULL COMMENT '일반전화',
  `mb_phone` VARCHAR(13) NOT NULL COMMENT '휴대전화',
  `mb_email` VARCHAR(50) NOT NULL COMMENT '이메일',
  `mb_addr1` VARCHAR(20) NOT NULL COMMENT '주소1',
  `mb_addr2` VARCHAR(100) NOT NULL COMMENT '주소2',
  `mb_addr3` VARCHAR(100) NOT NULL COMMENT '주소3',
  PRIMARY KEY (`mb_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '회원';


-- -----------------------------------------------------
-- Table `companion`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`category` (
  `ctgr_id` VARCHAR(10) NOT NULL COMMENT '분류코드',
  `ctgr_idref` VARCHAR(10) NULL DEFAULT NULL COMMENT '분류코드참조',
  `ctgr_name` VARCHAR(30) NOT NULL COMMENT '분류명',
  PRIMARY KEY (`ctgr_id`),
  INDEX `FK_category_category_ctgr_id` (`ctgr_idref` ASC) VISIBLE,
  CONSTRAINT `FK_category_category_ctgr_id`
    FOREIGN KEY (`ctgr_idref`)
    REFERENCES `companion`.`category` (`ctgr_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '분류';


-- -----------------------------------------------------
-- Table `companion`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`product` (
  `prdt_id` VARCHAR(10) NOT NULL COMMENT '상품코드',
  `prdt_name` VARCHAR(50) NOT NULL COMMENT '상품명',
  `prdt_price` INT(11) NOT NULL COMMENT '가격',
  `prdt_stock` INT(11) NOT NULL COMMENT '재고',
  `prdt_img` VARCHAR(100) NULL COMMENT '이미지',
  `prdt_ctgr_id` VARCHAR(45) NOT NULL COMMENT '분류번호',
  PRIMARY KEY (`prdt_id`),
  INDEX `FK_product_category_ctgr_id` (`prdt_ctgr_id` ASC) VISIBLE,
  CONSTRAINT `FK_product_category_ctgr_id`
    FOREIGN KEY (`prdt_ctgr_id`)
    REFERENCES `companion`.`category` (`ctgr_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '상품';


-- -----------------------------------------------------
-- Table `companion`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`cart` (
  `ct_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '장바구니번호',
  `ct_quantity` INT(11) NOT NULL COMMENT '수량',
  `ct_mb_id` VARCHAR(20) NOT NULL COMMENT '회원아이디',
  `ct_prdt_id` VARCHAR(10) NOT NULL COMMENT '상품코드',
  PRIMARY KEY (`ct_id`, `ct_prdt_id`, `ct_mb_id`),
  INDEX `FK_cart_member_mb_id` (`ct_mb_id` ASC) VISIBLE,
  INDEX `FK_cart_product_prdt_id` (`ct_prdt_id` ASC) VISIBLE,
  CONSTRAINT `FK_cart_member_mb_id`
    FOREIGN KEY (`ct_mb_id`)
    REFERENCES `companion`.`member` (`mb_id`),
  CONSTRAINT `FK_cart_product_prdt_id`
    FOREIGN KEY (`ct_prdt_id`)
    REFERENCES `companion`.`product` (`prdt_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '장바구니';


-- -----------------------------------------------------
-- Table `companion`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`coupon` (
  `cp_id` INT(11) NOT NULL COMMENT '쿠폰코드',
  `cp_name` VARCHAR(30) NOT NULL COMMENT '쿠폰명',
  `cp_enddate` DATETIME NOT NULL COMMENT '기한',
  `cp_sale` INT(11) NOT NULL COMMENT '할인율',
  PRIMARY KEY (`cp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '쿠폰';


-- -----------------------------------------------------
-- Table `companion`.`coupon_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`coupon_list` (
  `cplist_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '쿠폰목록번호',
  `cplist_cp_id` INT(11) NOT NULL COMMENT '쿠폰코드',
  `cplist_mb_id` VARCHAR(20) NOT NULL COMMENT '회원아이디',
  PRIMARY KEY (`cplist_id`),
  INDEX `FK_coupon_list_coupon_cp_id` (`cplist_cp_id` ASC) VISIBLE,
  INDEX `FK_coupon_list_member_mb_id` (`cplist_mb_id` ASC) VISIBLE,
  CONSTRAINT `FK_coupon_list_coupon_cp_id`
    FOREIGN KEY (`cplist_cp_id`)
    REFERENCES `companion`.`coupon` (`cp_id`),
  CONSTRAINT `FK_coupon_list_member_mb_id`
    FOREIGN KEY (`cplist_mb_id`)
    REFERENCES `companion`.`member` (`mb_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '쿠폰목록';


-- -----------------------------------------------------
-- Table `companion`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`order` (
  `ord_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '주문번호',
  `ord_date` DATETIME NOT NULL COMMENT '주문일',
  `ord_amount` INT(11) NOT NULL COMMENT '총가격',
  `ord_name` VARCHAR(10) NOT NULL COMMENT '수령인',
  `ord_tel` VARCHAR(13) NULL DEFAULT NULL COMMENT '수령인 일반전화',
  `ord_phone` VARCHAR(13) NOT NULL COMMENT '수령인 휴대전화',
  `ord_addr1` VARCHAR(20) NOT NULL COMMENT '주소1',
  `ord_addr2` VARCHAR(100) NOT NULL COMMENT '주소2',
  `ord_addr3` VARCHAR(100) NOT NULL COMMENT '주소3',
  `ord_type` VARCHAR(10) NOT NULL COMMENT '결제방법',
  `ord_state` VARCHAR(10) NOT NULL DEFAULT '결제대기' COMMENT '주문상태',
  `ord_mb_id` VARCHAR(20) NOT NULL COMMENT '회원아이디',
  PRIMARY KEY (`ord_id`, `ord_mb_id`),
  INDEX `FK_order_member_mb_id` (`ord_mb_id` ASC) VISIBLE,
  CONSTRAINT `FK_order_member_mb_id`
    FOREIGN KEY (`ord_mb_id`)
    REFERENCES `companion`.`member` (`mb_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '주문';


-- -----------------------------------------------------
-- Table `companion`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`delivery` (
  `dlvr_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '택배번호',
  `dlvr_state` VARCHAR(10) NOT NULL COMMENT '택배상태',
  `dlvr_number` VARCHAR(30) NOT NULL COMMENT '송장번호',
  `dlvr_ord_id` INT(11) NOT NULL COMMENT '주문번호',
  PRIMARY KEY (`dlvr_id`, `dlvr_ord_id`),
  INDEX `FK_delivery_order_ord_id` (`dlvr_ord_id` ASC) VISIBLE,
  CONSTRAINT `FK_delivery_order_ord_id`
    FOREIGN KEY (`dlvr_ord_id`)
    REFERENCES `companion`.`order` (`ord_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '택배';


-- -----------------------------------------------------
-- Table `companion`.`emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`emp` (
  `emp_id` VARCHAR(20) NOT NULL COMMENT '직원아이디',
  `emp_pw` VARCHAR(30) NOT NULL COMMENT '비밀번호',
  `emp_name` VARCHAR(10) NOT NULL COMMENT '이름',
  `emp_phone` VARCHAR(13) NOT NULL COMMENT '휴대전화',
  PRIMARY KEY (`emp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '직원';


-- -----------------------------------------------------
-- Table `companion`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`event` (
  `evt_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '이벤트글번호',
  `evt_title` VARCHAR(50) NOT NULL COMMENT '제목',
  `evt_content` TEXT NOT NULL COMMENT '내용',
  `evt_date` DATETIME NOT NULL COMMENT '작성일자',
  `evt_cnt` INT(11) NOT NULL DEFAULT '0' COMMENT '조회수',
  `evt_img` VARCHAR(100) NULL COMMENT 'img',
  PRIMARY KEY (`evt_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '이벤트';


-- -----------------------------------------------------
-- Table `companion`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`notice` (
  `ntc_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '공지글번호',
  `ntc_title` VARCHAR(50) NOT NULL COMMENT '제목',
  `ntc_content` TEXT NOT NULL COMMENT '내용',
  `ntc_date` DATETIME NOT NULL COMMENT '작성일자',
  `ntc_cnt` INT(11) NOT NULL DEFAULT '0' COMMENT '조회수',
  `ntc_img` VARCHAR(100) NULL COMMENT '이미지',
  PRIMARY KEY (`ntc_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '공지사항';


-- -----------------------------------------------------
-- Table `companion`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`order_detail` (
  `orddetail_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '주문상세번호',
  `orddetail_price` INT(11) NOT NULL COMMENT '가격',
  `orddetail_quantity` INT(11) NOT NULL COMMENT '수량',
  `orddetail_prdt_id` VARCHAR(10) NOT NULL COMMENT '상품코드',
  `orddetail_ord_id` INT(11) NOT NULL COMMENT '주문번호',
  PRIMARY KEY (`orddetail_id`, `orddetail_ord_id`, `orddetail_prdt_id`),
  INDEX `FK_order_detail_product_prdt_id` (`orddetail_prdt_id` ASC) VISIBLE,
  INDEX `FK_order_detail_order_ord_id` (`orddetail_ord_id` ASC) VISIBLE,
  CONSTRAINT `FK_order_detail_order_ord_id`
    FOREIGN KEY (`orddetail_ord_id`)
    REFERENCES `companion`.`order` (`ord_id`),
  CONSTRAINT `FK_order_detail_product_prdt_id`
    FOREIGN KEY (`orddetail_prdt_id`)
    REFERENCES `companion`.`product` (`prdt_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '주문상세';


-- -----------------------------------------------------
-- Table `companion`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`payment` (
  `pmt_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '결제번호',
  `pmt_date` DATETIME NULL DEFAULT NULL COMMENT '결제일',
  `pmt_state` VARCHAR(10) NOT NULL DEFAULT '결재대기' COMMENT '결제상태',
  `pmt_ord_id` INT(11) NOT NULL COMMENT '주문번호',
  `pmt_mb_id` VARCHAR(20) NOT NULL COMMENT '회원아이디',
  PRIMARY KEY (`pmt_id`, `pmt_ord_id`, `pmt_mb_id`),
  INDEX `FK_payment_member_mb_id` (`pmt_mb_id` ASC) VISIBLE,
  INDEX `FK_payment_order_ord_id` (`pmt_ord_id` ASC) VISIBLE,
  CONSTRAINT `FK_payment_member_mb_id`
    FOREIGN KEY (`pmt_mb_id`)
    REFERENCES `companion`.`member` (`mb_id`),
  CONSTRAINT `FK_payment_order_ord_id`
    FOREIGN KEY (`pmt_ord_id`)
    REFERENCES `companion`.`order` (`ord_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '결제';


-- -----------------------------------------------------
-- Table `companion`.`point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`point` (
  `pt_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '적립금번호',
  `pt_money` INT(11) NOT NULL COMMENT '적립금액',
  `pt_mb_id` VARCHAR(20) NOT NULL COMMENT '회원아이디',
  PRIMARY KEY (`pt_id`, `pt_mb_id`),
  INDEX `FK_point_member_mb_id` (`pt_mb_id` ASC) VISIBLE,
  CONSTRAINT `FK_point_member_mb_id`
    FOREIGN KEY (`pt_mb_id`)
    REFERENCES `companion`.`member` (`mb_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '적립금';


-- -----------------------------------------------------
-- Table `companion`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`question` (
  `qst_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '문의글번호',
  `qst_product` VARCHAR(10) NOT NULL COMMENT '상품코드',
  `qst_title` VARCHAR(50) NOT NULL COMMENT '제목',
  `qst_content` TEXT NOT NULL COMMENT '내용',
  `qst_date` DATETIME NOT NULL COMMENT '작성일자',
  `qst_cnt` INT(11) NOT NULL DEFAULT '0' COMMENT '조회수',
  `pst_img` VARCHAR(100) NULL COMMENT '이미지',
  `pst_secret` INT NOT NULL DEFAULT 0 COMMENT '공개여부',
  `qst_grpno` INT(11) NOT NULL COMMENT '글그룹번호',
  `qst_grpord` INT(11) NOT NULL COMMENT '글그룹순서',
  `qst_depth` INT(11) NOT NULL COMMENT '글깊이',
  `qst_mb_id` VARCHAR(20) NOT NULL COMMENT '회원아이디',
  PRIMARY KEY (`qst_id`, `qst_mb_id`),
  INDEX `FK_question_member_mb_id` (`qst_mb_id` ASC) VISIBLE,
  CONSTRAINT `FK_question_member_mb_id`
    FOREIGN KEY (`qst_mb_id`)
    REFERENCES `companion`.`member` (`mb_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '문의';


-- -----------------------------------------------------
-- Table `companion`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`review` (
  `rv_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '후기글번호',
  `rv_product` VARCHAR(10) NOT NULL COMMENT '상품코드',
  `rv_title` VARCHAR(50) NOT NULL COMMENT '제목',
  `rv_content` TEXT NOT NULL COMMENT '내용',
  `rv_date` DATETIME NOT NULL COMMENT '작성일자',
  `rv_cnt` INT(11) NOT NULL DEFAULT '0' COMMENT '조회수',
  `rv_img` VARCHAR(100) NULL COMMENT '이미지',
  `rv_mb_id` VARCHAR(20) NOT NULL COMMENT '회원아이디',
  PRIMARY KEY (`rv_id`, `rv_mb_id`),
  INDEX `FK_review_member_mb_id` (`rv_mb_id` ASC) VISIBLE,
  CONSTRAINT `FK_review_member_mb_id`
    FOREIGN KEY (`rv_mb_id`)
    REFERENCES `companion`.`member` (`mb_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '후기';


-- -----------------------------------------------------
-- Table `companion`.`product_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`product_detail` (
  `prdtdetail_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '상품상세번호',
  `prdtdetail_prdt_id` VARCHAR(10) NOT NULL COMMENT '상품코드',
  `prdtdetail_qst_id` INT(11) NULL DEFAULT NULL COMMENT '문의글번호',
  `prdtdetail_rv_id` INT(11) NULL DEFAULT NULL COMMENT '후기글번호',
  PRIMARY KEY (`prdtdetail_id`, `prdtdetail_prdt_id`),
  INDEX `FK_product_detail_product_prdt_id` (`prdtdetail_prdt_id` ASC) VISIBLE,
  INDEX `FK_product_detail_question_qst_id` (`prdtdetail_qst_id` ASC) VISIBLE,
  INDEX `FK_product_detail_review_rv_id` (`prdtdetail_rv_id` ASC) VISIBLE,
  CONSTRAINT `FK_product_detail_product_prdt_id`
    FOREIGN KEY (`prdtdetail_prdt_id`)
    REFERENCES `companion`.`product` (`prdt_id`),
  CONSTRAINT `FK_product_detail_question_qst_id`
    FOREIGN KEY (`prdtdetail_qst_id`)
    REFERENCES `companion`.`question` (`qst_id`),
  CONSTRAINT `FK_product_detail_review_rv_id`
    FOREIGN KEY (`prdtdetail_rv_id`)
    REFERENCES `companion`.`review` (`rv_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '상품상세';


-- -----------------------------------------------------
-- Table `companion`.`qa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`qa` (
  `qa_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Q&A글번호',
  `qa_title` VARCHAR(50) NOT NULL COMMENT '제목',
  `qa_content` TEXT NOT NULL COMMENT '내용',
  `qa_writer` VARCHAR(20) NOT NULL COMMENT '작성자',
  `qa_date` DATETIME NOT NULL COMMENT '작성일자',
  `qa_cnt` INT(11) NOT NULL DEFAULT '0' COMMENT '조회수',
  `qa_img` VARCHAR(100) NULL COMMENT '이미지',
  `qa_mb_id` VARCHAR(20) NOT NULL COMMENT '회원아이디',
  PRIMARY KEY (`qa_id`, `qa_mb_id`),
  INDEX `FK_qa_member_mb_id` (`qa_mb_id` ASC) VISIBLE,
  CONSTRAINT `FK_qa_member_mb_id`
    FOREIGN KEY (`qa_mb_id`)
    REFERENCES `companion`.`member` (`mb_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Q&A';


-- -----------------------------------------------------
-- Table `companion`.`qa_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`qa_comment` (
  `qacmt_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '댓글번호',
  `qacmt_content` TEXT NOT NULL COMMENT '내용',
  `qacmt_writer` VARCHAR(20) NOT NULL COMMENT '작성자',
  `qacmt_date` DATETIME NOT NULL COMMENT '작성일자',
  `qacmt_grpno` INT(11) NOT NULL COMMENT '댓글그룹번호',
  `qacmt_grpord` INT(11) NOT NULL COMMENT '댓글그룹순서',
  `qacmt_depth` INT(11) NOT NULL COMMENT '댓글깊이',
  `qacmt_qa_id` INT(11) NOT NULL COMMENT '게시글번호',
  PRIMARY KEY (`qacmt_id`, `qacmt_qa_id`),
  INDEX `FK_qa_comment_qa_qa_id` (`qacmt_qa_id` ASC) VISIBLE,
  CONSTRAINT `FK_qa_comment_qa_qa_id`
    FOREIGN KEY (`qacmt_qa_id`)
    REFERENCES `companion`.`qa` (`qa_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Q&A_댓글';


-- -----------------------------------------------------
-- Table `companion`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`service` (
  `svc_id` VARCHAR(10) NOT NULL COMMENT '서비스코드',
  `svc_name` VARCHAR(30) NOT NULL COMMENT '서비스명',
  `svc_price` INT(11) NOT NULL COMMENT '가격',
  `svc_size` VARCHAR(20) NOT NULL COMMENT '크기',
  PRIMARY KEY (`svc_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '호텔서비스';


-- -----------------------------------------------------
-- Table `companion`.`reserve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`reserve` (
  `rsv_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '예약번호',
  `rsv_date` DATETIME NOT NULL COMMENT '예약일',
  `rsv_checkin` DATETIME NOT NULL COMMENT '입실일',
  `rsv_checkout` DATETIME NOT NULL COMMENT '퇴실일',
  `rsv_type` VARCHAR(20) NULL DEFAULT NULL COMMENT '반려견종',
  `rsv_age` INT(11) NULL DEFAULT NULL COMMENT '반려견나이',
  `rsv_msg` VARCHAR(500) NULL DEFAULT NULL COMMENT '기타',
  `rsv_svc_id` VARCHAR(10) NOT NULL COMMENT '서비스코드',
  `rsv_mb_id` VARCHAR(20) NOT NULL COMMENT '회원아이디',
  PRIMARY KEY (`rsv_id`, `rsv_mb_id`),
  INDEX `FK_reserve_service_svc_id` (`rsv_svc_id` ASC) VISIBLE,
  INDEX `FK_reserve_member_mb_id` (`rsv_mb_id` ASC) VISIBLE,
  CONSTRAINT `FK_reserve_member_mb_id`
    FOREIGN KEY (`rsv_mb_id`)
    REFERENCES `companion`.`member` (`mb_id`),
  CONSTRAINT `FK_reserve_service_svc_id`
    FOREIGN KEY (`rsv_svc_id`)
    REFERENCES `companion`.`service` (`svc_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '예약';


-- -----------------------------------------------------
-- Table `companion`.`review_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companion`.`review_comment` (
  `rvcmt_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '댓글번호',
  `rvcmt_title` TEXT NOT NULL COMMENT '내용',
  `rvcmt_writer` VARCHAR(20) NOT NULL COMMENT '작성자',
  `rvcmt_date` DATETIME NOT NULL COMMENT '작성일자',
  `rvcmt_grpno` INT(11) NOT NULL COMMENT '댓글그룹번호',
  `rvcmt_grpord` INT(11) NOT NULL COMMENT '댓글그룹순서',
  `rvcmt_depth` INT(11) NOT NULL COMMENT '댓글깊이',
  `rvcmt_rv_id` INT(11) NOT NULL COMMENT '게시글번호',
  PRIMARY KEY (`rvcmt_id`, `rvcmt_rv_id`),
  INDEX `FK_review_comment_review_rv_id` (`rvcmt_rv_id` ASC) VISIBLE,
  CONSTRAINT `FK_review_comment_review_rv_id`
    FOREIGN KEY (`rvcmt_rv_id`)
    REFERENCES `companion`.`review` (`rv_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '후기_댓글';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
